services:
  simplelogin-mailcow-bridge:
    image: ghcr.io/ruakij/simplelogin-mailcow-bridge:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MAILCOW_ADMIN_API_URL=
      - MAILCOW_ADMIN_API_KEY=
      - MAILCOW_AUTH_METHOD=IMAP
      - MAILCOW_SERVER_ADDRESS=
      - CORS_ALLOW_ORIGIN=
      - ALIAS_VALIDITY_PERIOD=10
      # Auth caching configuration
      - AUTH_CACHE_TTL=300  # in seconds, 0 to disable
      # Logging configuration
      - LOG_LEVEL=INFO      # Available levels: DEBUG, INFO, WARN, ERROR
      - LOG_COLOR=true      # Enable/disable colored logs (true/false)
      # Template patterns:
      # Use {words} for random words, {words:3} for 3 words
      # Use {word-chars} for alphanumeric strings starting with a letter
      # Use {chars} for alphanumeric + special chars (.-_) starting with a letter
      # Use {names}, {firstname}, {lastname}, {middlename}, {nickname} for name-like strings
      # Use length controls: {word-chars:8} for exactly 8 chars, {firstname:4,8} for 4-8 chars
      # Use %d to include domain from user's email
      - ALIAS_GENERATION_PATTERN={firstname}.{lastname}@%d
